name: Swift

on:
  push:
    branches: [ canon ]
  pull_request:
    branches: [ canon ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9" 
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
